export const GET_REQUEST = 'GET_REQUEST';

export const GET_EXAMPLE_SUCCESS = 'GET_EXAMPLE_SUCCESS';
export const GET_EXAMPLE_FAILURE = 'GET_EXAMPLE_FAILURE';

export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS';
export const GET_POKEMON_FAILURE = 'GET_POKEMON_FAILURE';